import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Provider from "@/components/Provider";




const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <Provider>
      <html lang="en">

        <body className={inter.className}>



          <Header />
          <main className="lg:ml-[251px]">{children}</main>





        </body>

      </html>
    </Provider>
  );
}
